"$schema": https://json-schema.org/draft/2020-12/schema
description: 'Example of a simple GeoJSON Feature specialisation using an externally defined JSON-LD context.'
$defs:
  MyFeature:
    allOf:
      - $ref: bblocks://ogc.geo.features.feature
      - properties:
          properties:
            $ref: https://raw.githubusercontent.com/smart-data-models/dataModel.ACRIS/master/AirportFacility/schema.json
anyOf:
  - $ref: "#/$defs/MyFeature"
